services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=integrainfotecnico
      - POSTGRES_PASSWORD=integrainfotecnico123
      - POSTGRES_DB=integrainfotecnicodb
    volumes:
      - students_pg_data:/bitnami/postgresql


volumes:
  students_pg_data: